spring:
  application:
    name: sold-easy
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sold_easy
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true

    locations: db/migrations
server:
  port: 8081
logging:
  level:
    org.org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /api-docs


