create sequence car_id_gen start with 1 increment by 50;
create sequence client_id_gen start with 1 increment by 50;
create sequence colour_id_gen start with 1 increment by 50;
create sequence condition_history_id_gen start with 1 increment by 50;
create sequence consumption_id_gen start with 1 increment by 50;
create sequence damage_id_gen start with 1 increment by 50;
create sequence detail_id_gen start with 1 increment by 50;
create sequence documentation_id_gen start with 1 increment by 50;
create sequence engine_id_gen start with 1 increment by 50;
create sequence external_extra_gen start with 1 increment by 50;
create sequence externalcolour_id_gen start with 1 increment by 50;
create sequence external_extra_type_id_gen start with 1 increment by 50;
create sequence extra_id_gen start with 1 increment by 50;
create sequence finance_history_id_gen start with 1 increment by 50;
create sequence fuel_id_gen start with 1 increment by 50;
create sequence history_id_gen start with 1 increment by 50;
create sequence internal_extra_gen start with 1 increment by 50;
create sequence internal_extra_type_id_gen start with 1 increment by 50;
create sequence license_history_id_gen start with 1 increment by 50;
create sequence make_id_gen start with 1 increment by 50;
create sequence owner_id_gen start with 1 increment by 50;
create sequence ownershiphistory_id_gen start with 1 increment by 50;
create sequence profile_id_gen start with 1 increment by 50;
create sequence sale_id_gen start with 1 increment by 50;
create sequence service_id_gen start with 1 increment by 50;
create sequence service_history_id_gen start with 1 increment by 50;
create sequence transmission_id_gen start with 1 increment by 50;
create sequence wheels_id_gen start with 1 increment by 50;
create table car (history_id bigint unique, id bigint not null, make_id bigint unique, owner_id bigint unique, primary key (id));
create table car_extras (car_id bigint not null, extras_id bigint not null unique);
create table client (id bigint not null, cell_phone_no varchar(255), email_address varchar(255), first_name varchar(255), id_number varchar(255), last_name varchar(255), residential_address varchar(255), primary key (id));
create table colour (external_colour_id bigint unique, id bigint not null, internal_colour varchar(255), primary key (id));
create table condition_history (id bigint not null, condition varchar(255) check (condition in ('POOR','BAD','FAIR','GOOD','EXCELLENT')), primary key (id));
create table condition_history_damages (condition_history_id bigint not null, damages_id bigint not null unique);
create table consumption (rate float(53) not null, id bigint not null, unit varchar(255) check (unit in ('KMPER100','LPERKM','LPERHOUR','KMPERL')), primary key (id));
create table damage (damage smallint check (damage between 0 and 2), id bigint not null, description varchar(255), imageurl varchar(255), primary key (id));
create table details (year integer, id bigint not null, chasis_number varchar(255), make varchar(255), model varchar(255), primary key (id));
create table documentation (id bigint not null, document_type varchar(255) check (document_type in ('NATIS','ID')), name varchar(255), primary key (id));
create table engine (no_of_cylinders integer, power integer, torque integer, id bigint not null, engine_number varchar(255), primary key (id));
create table external_colour (colourtype smallint check (colourtype between 0 and 3), id bigint not null, colour varchar(255), primary key (id));
create table external_extra (external_extra_type_id bigint unique, id bigint not null, primary key (id));
create table external_extra_type (id bigint not null, name varchar(255), primary key (id));
create table extras (id bigint not null, primary key (id));
create table extras_external_extras (external_extras_id bigint not null unique, extras_id bigint not null);
create table extras_internal_extras (extras_id bigint not null, internal_extras_id bigint not null unique);
create table finance_history (financed boolean not null, financed_amount float(53) not null, outstanding_amount float(53) not null, id bigint not null, primary key (id));
create table fuel (capacity integer, range integer, consumption_id bigint unique, id bigint not null, system varchar(255), type varchar(255), primary key (id));
create table history (condition_history_id bigint unique, finance_history_id bigint unique, id bigint not null, license_history_id bigint unique, service_history_id bigint unique, primary key (id));
create table history_ownership_history (history_id bigint not null, ownership_history_id bigint not null unique);
create table internal_extra (id bigint not null, internal_extra_type_id bigint unique, primary key (id));
create table internal_extra_type (id bigint not null, name varchar(255), primary key (id));
create table license_history (valid_license boolean not null, date_of_expiry timestamp(6), id bigint not null, vehicle_register varchar(255), primary key (id));
create table make (transmission_type smallint unique, colour_id bigint unique, details_id bigint unique, engine_id bigint unique, fuel_id bigint unique, id bigint not null, wheels_id bigint unique, primary key (id));
create table owner (id bigint not null, alt_no varchar(255), cell_no varchar(255), email varchar(255), id_number varchar(255), name varchar(255), surname varchar(255), primary key (id));
create table ownership_history (mileage integer, ownership_duration integer, purchase_price float(53) not null, trade_in_value float(53) not null, warranty boolean not null, buy_date timestamp(6), id bigint not null, sell_date timestamp(6), puchase_location varchar(255), primary key (id));
create table ownership_history_documentations (documentations_id bigint not null unique, ownership_history_id bigint not null);
create table profile (client_id bigint unique, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table profile_sales (profile_id bigint not null, sales_id bigint not null unique);
create table sale (registered boolean, car_id bigint unique, client_id bigint unique, id bigint not null, profile_id bigint unique, primary key (id));
create table service (service_milleage integer, id bigint not null, service_date timestamp(6), service_dealer varchar(255), primary key (id));
create table service_history (id bigint not null, service_plan varchar(255), primary key (id));
create table service_history_services (service_history_id bigint not null, services_id bigint not null unique);
create table transmission (type smallint not null check (type between 0 and 1), drive_wheels varchar(255), no_of_gears varchar(255), primary key (type));
create table wheels (rim_size integer, id bigint not null, description varchar(255), tyresize varchar(255), primary key (id));
alter table if exists car add constraint FKmdpapolqn239iavtjbpnaimpe foreign key (history_id) references history;
alter table if exists car add constraint FK8dnhr9fn281npgs59xx0o1qfj foreign key (make_id) references make;
alter table if exists car add constraint FK4ec59hmbtvq3tjp1xcluis1j6 foreign key (owner_id) references owner;
alter table if exists car_extras add constraint FKp820p1w4tauhrh38dj1p2xow3 foreign key (extras_id) references extras;
alter table if exists car_extras add constraint FKbeymowqbxnc932yv370mbxl7i foreign key (car_id) references car;
alter table if exists colour add constraint FKdi7468gb9socsrhu4s89ygju6 foreign key (external_colour_id) references external_colour;
alter table if exists condition_history_damages add constraint FKhr23mxxcrwo8d4sbsimbyn61v foreign key (damages_id) references damage;
alter table if exists condition_history_damages add constraint FKgtihjsevw44abq5ypoil485t9 foreign key (condition_history_id) references condition_history;
alter table if exists external_extra add constraint FK5vdah1mc5531alvyb70ajm88 foreign key (external_extra_type_id) references external_extra_type;
alter table if exists extras_external_extras add constraint FKl7qwnbdacb1f9vr6d4id5o3g foreign key (external_extras_id) references external_extra;
alter table if exists extras_external_extras add constraint FKeruy09spu16kwbc3pcapyk4y foreign key (extras_id) references extras;
alter table if exists extras_internal_extras add constraint FKbt5ji5x0dkb36snwugd4rgx2e foreign key (internal_extras_id) references internal_extra;
alter table if exists extras_internal_extras add constraint FKbo7n5328lv96r8lqbs6g6aq22 foreign key (extras_id) references extras;
alter table if exists fuel add constraint FK86narms1lw38y99146r8ygtaa foreign key (consumption_id) references consumption;
alter table if exists history add constraint FK6anl7sano3pn94b924fygm3w1 foreign key (condition_history_id) references condition_history;
alter table if exists history add constraint FK7jhbfjtix4t0umc57a3849677 foreign key (finance_history_id) references finance_history;
alter table if exists history add constraint FKanbqyraeakewt62h5alkos4ch foreign key (license_history_id) references license_history;
alter table if exists history add constraint FK8mcka548ajuohxwvqohw51h26 foreign key (service_history_id) references service_history;
alter table if exists history_ownership_history add constraint FKk8uh1cw9emp478q65naufctpi foreign key (ownership_history_id) references ownership_history;
alter table if exists history_ownership_history add constraint FKnsniclplmhd42s2cqswif5gb4 foreign key (history_id) references history;
alter table if exists internal_extra add constraint FK381s0e38tpog5sw0gtn23sext foreign key (internal_extra_type_id) references internal_extra_type;
alter table if exists make add constraint FKk3u1skletm7c9t8eojl9mjrno foreign key (colour_id) references colour;
alter table if exists make add constraint FK30hbb2093ylv7vja7jklkxiqs foreign key (details_id) references details;
alter table if exists make add constraint FK4bxbrj0dbttd7me1rp4k3ts7d foreign key (engine_id) references engine;
alter table if exists make add constraint FKphwy9ybkk3chrx7s468i8k911 foreign key (fuel_id) references fuel;
alter table if exists make add constraint FK7mwho2p94c8niom7ga0teb80o foreign key (transmission_type) references transmission;
alter table if exists make add constraint FKgg5rumfcg998x5yw3tvirfmcm foreign key (wheels_id) references wheels;
alter table if exists ownership_history_documentations add constraint FK75pr4vj98fddj5rctcw0191n5 foreign key (documentations_id) references documentation;
alter table if exists ownership_history_documentations add constraint FKfee82190lcmsldp3o8r2w9dal foreign key (ownership_history_id) references ownership_history;
alter table if exists profile add constraint FK156lhmbobu768duxishl8vgr6 foreign key (client_id) references client;
alter table if exists profile_sales add constraint FK7q34xyq9c9ptnem15dwo4f25g foreign key (sales_id) references sale;
alter table if exists profile_sales add constraint FK5h9693so957q99gujboc6bjkf foreign key (profile_id) references profile;
alter table if exists sale add constraint FK99jdj9wyee14950vox07kjqdj foreign key (car_id) references car;
alter table if exists sale add constraint FKon0o9ba5ajsnwivekhl1tfjiy foreign key (client_id) references client;
alter table if exists sale add constraint FK9breyxo0vo928x1chwfiluka1 foreign key (profile_id) references profile;
alter table if exists service_history_services add constraint FKnr3wjkjq0njbq2vqkewdyk83x foreign key (services_id) references service;
alter table if exists service_history_services add constraint FKlc38skh8pvjschr04itsj983a foreign key (service_history_id) references service_history;